### ISSUE TITLE
Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by wangtao666** [janmi/vue-citys-picker#2]
this.$refs[name].open()，这里的open没定义，还是我引用以有问题，请指正，谢谢！

**Comment by janmi** [comment]
请提交具体的代码或者可重现BUG的示例

**Comment by janmi** [comment]
请提交具体的代码或者可重现BUG的示例

**Comment by wangtao666** [comment]
main.js配置如下：
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'
import $ from 'jquery'
import animate from 'vue2-animate/dist/vue2-animate.min.css'
import vueCitysPicker from './assets/js/vue-citys-picker.js'

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
test.vue配置如下：
<template>
	<div id="app2">
		<span @click="show('address')">213123123</span>
		<citys-picker :city="data" :init-value="defaultVal" @confirm="confirm" ref="citys"></citys-picker>
	</div>
</template>

<script>
	require ('../assets/css/vue-citys-picker.css');
//	import CitysPicker from '../assets/js/vue-citys-picker';
	import CitysPicker from 'vue-citys-picker';
	
	export default {
	  name: 'app2',
	  components: {
	    CitysPicker
	  },
	  data () {
	    return {
	      data: CityData,
	      defaultVal: [{
	        name: '天津',
	        value: '120000'
	      }, {
	        name: '天津市',
	        value: '120100'
	      }, {
	        name: '北辰区',
	        value: '120113'
	      }]
	    }
	  },
	  methods: {
	    confirm (values) {
	      console.log(values)
	    },
	    show (name) {
	      this.$refs[name].open()
	    }
	  }
	}
</script>

<style>
</style>

**Comment by wangtao666** [comment]
![default](https://user-images.githubusercontent.com/26650045/29441706-b9d06efe-83ff-11e7-9cfe-b2a43ee9390f.png)
![default](https://user-images.githubusercontent.com/26650045/29441708-baa20cac-83ff-11e7-85e0-1ac1152741f2.png)

**Comment by wangtao666** [comment]
如果方便可以添加一下您的qq，或者微信，或者您添加一下我：QQ602697966

**Comment by janmi** [comment]
CityData 并没有打包到 vue-citys-picker.js 中，请单独引用
example 中有使用一份 CityData 数据，如果该数据符合你的要求，可以直接使用

**Comment by wangtao666** [comment]
require ('vue-citys-picker/example/CityData.json');我在test.vue里面引入了json文件，但是还是报错，能加一下您的qq吗

**Comment by wangtao666** [comment]
this.$refs[name].open()，这里的open没定义，还是我引用以有问题，请指正，谢谢！
